#!/bin/bash

if [ $# -lt 1 ];
then
	echo "Aufruf $0 <ServerName>"
	exit 1
fi

SrvName=$1

CfgBase=/root/vpn_cfg
ServerCfgBase=$CfgBase/$SrvName
ServerKeysDir=$ServerCfgBase/keys
ServerCfgFile=$ServerCfgBase/$ServerName.conf
ClientCfgDir=$ServerCfgBase/ccd
ServerCfgVars=$ServerCfgBase/vars

rm -rf $ServerCfgBase
rm /etc/openvpn/$SrvName.conf

