#!/bin/bash

if [ $# -lt 2 ];
then
        echo "Aufruf $0 <ServerName> <ClientName>"
        exit 1
fi

SrvName=$1
ClientName=$2
ClientSubNet=$3
ClientSubNetMask=$4

CfgBase=/root/vpn_cfg
ServerCfgBase=$CfgBase/$SrvName
ServerKeysDir=$ServerCfgBase/keys
ServerCfgFile=$ServerCfgBase/$ServerName.conf
ClientCfgDir=$ServerCfgBase/ccd
ServerCfgVars=$ServerCfgBase/vars

rm -f $ServerCfgBase/$ClientName.route

/root/vpn_admin/make_server_cfg $SrvName

rm -f $ClientCfgDir/$ClientName

rm -f /etc/openvpn/ccd/$SrvName/*
cp $ClientCfgDir/* /etc/openvpn/ccd/$SrvName/

